/**
 * Consent Flow for DCP Vault MCP Server
 *
 * Implements consent requirements from PRD Section 3.1.6:
 * - CN1: First interaction triggers consent
 * - CN2: CLI consent via terminal prompt
 * - CN3: Non-TTY consent via pending_consents table + polling
 * - CN5: Transactions above threshold ALWAYS require approval
 * - CN6: Session consent: 30 min idle timeout, 4 hour max
 * - CN7: Consent timeout: 5 minutes
 * - CN10: Default dev flow requires no server
 */

import * as readline from 'readline';
import { VaultStorage, VaultError } from '@dcprotocol/core';
import { ConsentRequest, ConsentResponse, ConsentAction } from './types.js';

// ============================================================================
// Constants
// ============================================================================

/** Consent timeout in milliseconds (5 minutes) */
const CONSENT_TIMEOUT_MS = 5 * 60 * 1000;

/** Polling interval for pending consents (500ms) */
const POLL_INTERVAL_MS = 500;

/** Session idle timeout in milliseconds (30 minutes) */
const SESSION_IDLE_TIMEOUT_MS = 30 * 60 * 1000;

/** Session max duration in milliseconds (4 hours) */
const SESSION_MAX_DURATION_MS = 4 * 60 * 60 * 1000;

// ============================================================================
// TTY Detection
// ============================================================================

/**
 * Check if stdin is a TTY (terminal)
 * MCP servers run as subprocesses, so they typically don't have TTY access
 */
export function isTTY(): boolean {
  return process.stdin.isTTY === true && process.stdout.isTTY === true;
}

// ============================================================================
// Consent Request Generation
// ============================================================================

/**
 * Create a consent request object
 */
export function createConsentRequest(
  agentName: string,
  action: ConsentAction,
  scope: string,
  options?: {
    description?: string;
    amount?: number;
    currency?: string;
    chain?: 'solana' | 'base' | 'ethereum';
  }
): ConsentRequest {
  // ID will be generated by storage layer
  const expiresAt = new Date(Date.now() + CONSENT_TIMEOUT_MS);

  return {
    id: '', // Will be set after storage.createPendingConsent
    agent_name: agentName,
    action,
    scope,
    description: options?.description,
    amount: options?.amount,
    currency: options?.currency,
    chain: options?.chain,
    expires_at: expiresAt.toISOString(),
  };
}

// ============================================================================
// TTY Consent (Terminal Prompt)
// ============================================================================

/**
 * Prompt for consent in terminal (TTY mode)
 *
 * @param request - Consent request details
 * @returns Consent response with approval mode
 */
export async function promptTTYConsent(request: ConsentRequest): Promise<ConsentResponse> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stderr, // Use stderr to keep stdout clean for MCP
  });

  return new Promise((resolve) => {
    // Build consent message
    let message = `\n--- DCP Vault Consent Request ---\n`;
    message += `Agent: ${request.agent_name}\n`;
    message += `Action: ${request.action}\n`;
    message += `Scope: ${request.scope}\n`;

    if (request.description) {
      message += `Description: ${request.description}\n`;
    }
    if (request.amount !== undefined && request.currency) {
      message += `Amount: ${request.amount} ${request.currency}\n`;
    }
    if (request.chain) {
      message += `Chain: ${request.chain}\n`;
    }

    message += `\nExpires: ${request.expires_at}\n`;
    message += `\n[a]pprove once / [s]ession / [d]eny: `;

    process.stderr.write(message);

    rl.question('', (answer) => {
      rl.close();

      const choice = answer.toLowerCase().trim();

      switch (choice) {
        case 'a':
        case 'approve':
        case 'once':
          resolve({ approved: true, mode: 'once' });
          break;
        case 's':
        case 'session':
          resolve({ approved: true, mode: 'session' });
          break;
        case 'd':
        case 'deny':
        case 'n':
        case 'no':
        default:
          resolve({ approved: false });
          break;
      }
    });

    // Handle timeout
    setTimeout(() => {
      rl.close();
      resolve({ approved: false });
    }, CONSENT_TIMEOUT_MS);
  });
}

// ============================================================================
// Non-TTY Consent (Polling)
// ============================================================================

/**
 * Request consent via pending_consents table and poll for resolution
 * User approves via `dcp approve <consent_id>` command
 *
 * @param storage - VaultStorage instance
 * @param request - Consent request details
 * @returns Consent response when resolved
 */
export async function requestPendingConsent(
  storage: VaultStorage,
  request: ConsentRequest
): Promise<ConsentResponse> {
  // Build details JSON from request options
  const details: Record<string, unknown> = {};
  if (request.description) details.description = request.description;
  if (request.amount !== undefined) details.amount = request.amount;
  if (request.currency) details.currency = request.currency;
  if (request.chain) details.chain = request.chain;

  // Insert pending consent into database
  // Storage layer generates the ID
  const consent = storage.createPendingConsent(
    request.agent_name,
    request.action,
    request.scope,
    Object.keys(details).length > 0 ? JSON.stringify(details) : undefined
  );

  // Update request with the generated ID
  request.id = consent.id;

  // Output instructions to stderr (won't interfere with MCP protocol)
  process.stderr.write(`\n--- DCP Vault Consent Required ---\n`);
  process.stderr.write(`Consent ID: ${consent.id}\n`);
  process.stderr.write(`Agent: ${request.agent_name}\n`);
  process.stderr.write(`Action: ${request.action}\n`);
  process.stderr.write(`Scope: ${request.scope}\n`);
  if (request.description) {
    process.stderr.write(`Description: ${request.description}\n`);
  }
  if (request.amount !== undefined && request.currency) {
    process.stderr.write(`Amount: ${request.amount} ${request.currency}\n`);
  }
  process.stderr.write(`\nTo approve, run:\n`);
  process.stderr.write(`  dcp approve ${consent.id}\n`);
  process.stderr.write(`\nTo deny, run:\n`);
  process.stderr.write(`  dcp approve ${consent.id} --deny\n\n`);

  // Poll for resolution
  const expiresAt = new Date(consent.expires_at).getTime();

  return new Promise((resolve, reject) => {
    const poll = () => {
      // Check if expired
      if (Date.now() >= expiresAt) {
        storage.resolveConsent(consent.id, 'expired');
        reject(new VaultError('CONSENT_TIMEOUT', 'Consent request expired', {
          consent_id: consent.id,
        }));
        return;
      }

      // Check consent status
      const currentConsent = storage.getPendingConsent(consent.id);

      if (!currentConsent) {
        // Consent was deleted (shouldn't happen)
        reject(new VaultError('CONSENT_NOT_FOUND', 'Consent request not found', {
          consent_id: consent.id,
        }));
        return;
      }

      if (currentConsent.status === 'approved') {
        // Check if a session was created during approval
        if (currentConsent.session_id) {
          resolve({
            approved: true,
            mode: 'session',
            session_id: currentConsent.session_id,
          });
        } else {
          resolve({
            approved: true,
            mode: 'once',
          });
        }
        return;
      }

      if (currentConsent.status === 'denied') {
        resolve({ approved: false });
        return;
      }

      if (currentConsent.status === 'expired') {
        reject(new VaultError('CONSENT_TIMEOUT', 'Consent request expired', {
          consent_id: consent.id,
        }));
        return;
      }

      // Still pending, poll again
      setTimeout(poll, POLL_INTERVAL_MS);
    };

    // Start polling
    poll();
  });
}

// ============================================================================
// Session Management
// ============================================================================

/**
 * Check if a session is still valid
 *
 * @param storage - VaultStorage instance
 * @param sessionId - Session ID to check
 * @returns true if session is valid, false otherwise
 */
export function isSessionValid(storage: VaultStorage, sessionId: string): boolean {
  const session = storage.getSession(sessionId);

  if (!session) {
    return false;
  }

  // Check if revoked
  if (session.revoked_at) {
    return false;
  }

  const now = Date.now();
  const expiresAt = new Date(session.expires_at).getTime();
  const createdAt = new Date(session.created_at).getTime();

  // Check if expired
  if (now >= expiresAt) {
    return false;
  }

  // Check idle timeout (30 minutes) if last_used_at is set
  if (session.last_used_at) {
    const lastUsedAt = new Date(session.last_used_at).getTime();
    if (now - lastUsedAt > SESSION_IDLE_TIMEOUT_MS) {
      return false;
    }
  }

  // Check max duration (4 hours)
  if (now - createdAt > SESSION_MAX_DURATION_MS) {
    return false;
  }

  return true;
}

/**
 * Check if a scope is covered by an existing session
 *
 * @param storage - VaultStorage instance
 * @param sessionId - Session ID to check
 * @param scope - Scope to check (e.g., 'wallet.sign' or 'address.home')
 * @returns true if scope is granted, false otherwise
 */
export function hasSessionScope(
  storage: VaultStorage,
  sessionId: string,
  scope: string
): boolean {
  if (!isSessionValid(storage, sessionId)) {
    return false;
  }

  const session = storage.getSession(sessionId);
  if (!session) {
    return false;
  }

  // Check if scope matches exactly or is covered by a wildcard
  for (const grantedScope of session.granted_scopes) {
    if (grantedScope === scope) {
      return true;
    }

    // Check wildcard patterns (e.g., 'address.*' covers 'address.home')
    if (grantedScope.endsWith('.*')) {
      const prefix = grantedScope.slice(0, -2);
      if (scope.startsWith(prefix + '.')) {
        return true;
      }
    }
  }

  return false;
}

/**
 * Touch session to update last_used_at
 */
export function touchSession(storage: VaultStorage, sessionId: string): void {
  storage.touchSession(sessionId);
}

// ============================================================================
// Unified Consent Flow
// ============================================================================

/**
 * Request consent using the appropriate method (TTY or polling)
 *
 * @param storage - VaultStorage instance
 * @param agentName - Name of the requesting agent
 * @param action - Action type (read, sign_tx, sign_message)
 * @param scope - Scope being accessed
 * @param options - Additional options (description, amount, etc.)
 * @returns Consent response
 */
export async function requestConsent(
  storage: VaultStorage,
  agentName: string,
  action: ConsentAction,
  scope: string,
  options?: {
    description?: string;
    amount?: number;
    currency?: string;
    chain?: 'solana' | 'base' | 'ethereum';
    sessionId?: string;
  }
): Promise<ConsentResponse> {
  // Check if we already have session consent
  if (options?.sessionId && hasSessionScope(storage, options.sessionId, scope)) {
    touchSession(storage, options.sessionId);
    return { approved: true, mode: 'session', session_id: options.sessionId };
  }

  // Create consent request
  const request = createConsentRequest(agentName, action, scope, options);

  // Use TTY prompt if available, otherwise poll
  if (isTTY()) {
    return promptTTYConsent(request);
  } else {
    return requestPendingConsent(storage, request);
  }
}

/**
 * Check if an amount requires mandatory approval (above threshold)
 * Transactions above approval threshold ALWAYS require consent, even with session
 */
export function requiresMandatoryApproval(
  amount: number | undefined,
  approvalThreshold: number
): boolean {
  if (amount === undefined) {
    return false;
  }
  return amount > approvalThreshold;
}
