/**
 * Vault connect bridge.
 *
 * The relay's OAuth AS must ask the VAULT that issued a connect-link to (a) redeem
 * it for an agent (producing the on-device match-code) and (b) report whether the
 * owner has approved. The vault — not the relay — is the source of truth: it
 * verifies the connect-link signature, generates the match-code, and runs the
 * on-device approval. The relay only orchestrates and issues tokens.
 *
 * This is the CONTROL plane (authorization handshake), distinct from the encrypted
 * DATA plane (vault operations). It carries no vault secrets and no key material.
 *
 * Production backs this with the relay↔vault WebSocket control channel; tests
 * inject a fake implementation.
 */

export interface BridgeRedeemInput {
  /** Vault that issued the link (routing target). */
  vaultId: string;
  /** The opaque connect-link token; the VAULT verifies + decodes it. */
  connectLink: string;
  /** Stable identifier for the redeeming agent — its DPoP JWK thumbprint (jkt). */
  redeemerKey: string;
  /** Server-derived source IP (for the on-device approval facts). */
  sourceIp?: string;
}

export interface BridgeRedeemResult {
  ok: boolean;
  agentId?: string;
  /** Match-code generated by the vault, shown on-device and returned to the agent. */
  matchCode?: string;
  reason?: string;
}

export interface BridgeApprovalInput {
  vaultId: string;
  agentId: string;
}

export interface BridgeApprovalResult {
  status: 'pending' | 'approved' | 'denied' | 'revoked' | 'unknown';
  /** Authoritative scope granted by the vault (only meaningful once approved). */
  scope?: string;
  /** Authoritative budget (display/audit). */
  budget?: { daily: number; currency: string; auto_approve_under: number };
}

export interface VaultConnectBridge {
  redeem(input: BridgeRedeemInput): Promise<BridgeRedeemResult>;
  approvalStatus(input: BridgeApprovalInput): Promise<BridgeApprovalResult>;
}

/** Default bridge used when no vault control channel is wired — fails closed. */
export class UnavailableVaultBridge implements VaultConnectBridge {
  async redeem(): Promise<BridgeRedeemResult> {
    return { ok: false, reason: 'vault_unreachable' };
  }
  async approvalStatus(): Promise<BridgeApprovalResult> {
    return { status: 'unknown' };
  }
}

/**
 * Data-plane bridge: forward an AUTHORIZED MCP request to the vault. The facade
 * has already verified the access token (audience) + DPoP proof; this carries the
 * authenticated agent identity so the vault can apply the right scopes/budget and
 * pop an on-device consent for sensitive actions.
 */
export interface AuthedMcpRequest {
  vaultId: string;
  /** Authenticated agent id (the access token subject). */
  agentId: string;
  /** Granted scope (space-delimited) from the access token. */
  scope: string;
  /** DPoP key thumbprint the token is bound to. */
  jkt: string;
  /** The MCP JSON-RPC request body. */
  body: unknown;
}

export interface McpDataBridge {
  forward(req: AuthedMcpRequest): Promise<{ status: number; body: unknown }>;
}

/** Default MCP data bridge — not wired yet; signals the data plane is unavailable. */
export class UnavailableMcpBridge implements McpDataBridge {
  async forward(): Promise<{ status: number; body: unknown }> {
    return {
      status: 503,
      body: { error: 'data_plane_unavailable', error_description: 'MCP bridge not configured' },
    };
  }
}
